In [19]:
# import the libraries and and load the dataset
import pandas as pd
df = pd.read_csv(r"C:\Users\PAVAN KALYAN\Desktop\DA_projects\customer_behaviour\customer_shopping_behavior.csv")

In [20]:
# exploring the dataset 
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [22]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [23]:
df.describe(include = 'all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [24]:
#checking for missing and null values in the dataset
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [25]:
# filling the missing values in Review Rating column with the median rating of the product category
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [26]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [27]:
#Renaming the column names for better readability and documentation

df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [28]:
#df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
#df = df.rename(columns={'Purchase Amount (USD)':'purchase_amount'})
import sqlalchemy
# Remove any parentheses, spaces, special chars
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(r'[^0-9a-zA-Z_]', '_', regex=True)
df = df.rename(columns={'purchase_amount__usd_':'purchase_amount_usd'})  # clean name

In [30]:
df = df.rename(columns={'purchase_amount__usd_':'purchase_amount_usd'})  # clean name
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_usd', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [31]:
#Feature engineer the dataset
labels = ['Teen', 'Adult', 'MIddle_aged', 'Senior']
df['age_group'] = pd.qcut(df['age'],q=4, labels = labels)

In [32]:
df[['age','age_group']].head(15)

    age    age_group
0    55  MIddle_aged
1    19         Teen
2    50  MIddle_aged
3    21         Teen
4    45  MIddle_aged
5    46  MIddle_aged
6    63       Senior
7    27         Teen
8    26         Teen
9    57  MIddle_aged
10   53  MIddle_aged
11   30         Teen
12   61       Senior
13   65       Senior
14   64       Senior

In [33]:
#creating a new column purchase_frequency_days

df['frequency_of_purchases'].unique()

array(['Fortnightly', 'Weekly', 'Annually', 'Quarterly', 'Bi-Weekly',
       'Monthly', 'Every 3 Months'], dtype=object)

In [34]:
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Annually': 365,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Monthly':30,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [35]:
df[['purchase_frequency_days','frequency_of_purchases']].head(15)

    purchase_frequency_days frequency_of_purchases
0                        14            Fortnightly
1                        14            Fortnightly
2                         7                 Weekly
3                         7                 Weekly
4                       365               Annually
5                         7                 Weekly
6                        90              Quarterly
7                         7                 Weekly
8                       365               Annually
9                        90              Quarterly
10                       14              Bi-Weekly
11                       14            Fortnightly
12                       14            Fortnightly
13                        7                 Weekly
14                        7                 Weekly

In [36]:
df[['discount_applied','promo_code_used']].head(15)

   discount_applied promo_code_used
0               Yes             Yes
1               Yes             Yes
2               Yes             Yes
3               Yes             Yes
4               Yes             Yes
5               Yes             Yes
6               Yes             Yes
7               Yes             Yes
8               Yes             Yes
9               Yes             Yes
10              Yes             Yes
11              Yes             Yes
12              Yes             Yes
13              Yes             Yes
14              Yes             Yes

In [38]:
(df['discount_applied'] == df['promo_code_used']).all()

True

In [37]:
#dropping promo_code_used column
df = df.drop('promo_code_used', axis=1)

In [38]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_usd', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

#connecting to the MySql database

In [39]:

!pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in c:\users\pavan kalyan\anaconda3\lib\site-packages (1.1.2)
Requirement already satisfied: sqlalchemy in c:\users\pavan kalyan\anaconda3\lib\site-packages (2.0.34)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\pavan kalyan\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\pavan kalyan\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)

In [43]:

from sqlalchemy import create_engine

# MySQL connection
username = "root"
password = "Pavan1132.."
host = "localhost"
port = "3306"
database = "customer_behavior"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

# Write DataFrame to MySQL
table_name = "customer"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

# Read back sample
pd.read_sql("SELECT * FROM customer LIMIT 5;", engine)

,customer_id,age,gender,item_purchased,category,purchase_amount_usd,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,MIddle_aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Teen,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,MIddle_aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Teen,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,MIddle_aged,365

In [44]:
#Q1. What is the total revenue generated by male vs. female customers?

q1 = """
SELECT gender, SUM(purchase_amount_usd) AS revenue
FROM customer
GROUP BY gender;
"""
df_q1 = pd.read_sql(q1, engine)
df_q1

   gender   revenue
0    Male  157890.0
1  Female   75191.0

In [45]:
#Q2. Which customers used a discount but still spent more than the average purchase amount?
q2 = """
SELECT customer_id, purchase_amount_usd
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount_usd >= (SELECT AVG(purchase_amount_usd) FROM customer);
"""
df_q2 = pd.read_sql(q2, engine)
df_q2

     customer_id  purchase_amount_usd
0              2                   64
1              3                   73
2              4                   90
3              7                   85
4              9                   97
..           ...                  ...
834         1667                   64
835         1671                   73
836         1673                   73
837         1674                   62
838         1676                   90

[839 rows x 2 columns]

In [46]:
pd.read_sql("SELECT * FROM customer LIMIT 5;", engine)

,customer_id,age,gender,item_purchased,category,purchase_amount_usd,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,MIddle_aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Teen,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,MIddle_aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Teen,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,MIddle_aged,365

In [47]:
#Which are the top 5 products with the highest average review rating?

q3 = """
SELECT item_purchased, ROUND(AVG(review_rating), 2) AS avg_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_product_rating DESC
LIMIT 5;
"""
df_q3 = pd.read_sql(q3, engine)
df_q3

  item_purchased  avg_product_rating
0         Gloves                3.86
1        Sandals                3.84
2          Boots                3.82
3            Hat                3.80
4        Handbag                3.78

In [48]:
#Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

q4 = """
SELECT shipping_type, ROUND(AVG(purchase_amount_usd), 2) AS avg_purchase
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;
"""
df_q4 = pd.read_sql(q4, engine)
df_q4

  shipping_type  avg_purchase
0       Express         60.48
1      Standard         58.46

In [49]:
#Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

q5 = """
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount_usd),2) AS avg_spend,
       ROUND(SUM(purchase_amount_usd),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;
"""
df_q5 = pd.read_sql(q5, engine)
df_q5

  subscription_status  total_customers  avg_spend  total_revenue
0                  No             2847      59.87       170436.0
1                 Yes             1053      59.49        62645.0

In [50]:
#Q6. Which 5 products have the highest percentage of purchases with discounts applied?

q6 = """
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;
"""
df_q6 = pd.read_sql(q6, engine)
df_q6

  item_purchased  discount_rate
0            Hat          50.00
1       Sneakers          49.66
2           Coat          49.07
3        Sweater          48.17
4          Pants          47.37

In [51]:
#Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 

q7 = """
WITH customer_type AS (
    SELECT customer_id, previous_purchases,
    CASE 
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment
    FROM customer
)
SELECT customer_segment, COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;
"""
df_q7 = pd.read_sql(q7, engine)
df_q7

  customer_segment  number_of_customers
0            Loyal                 3116
1        Returning                  701
2              New                   83

In [52]:
#Q8. What are the top 3 most purchased products within each category? 

q8 = """
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;
"""
df_q8 = pd.read_sql(q8, engine)
df_q8

    item_rank     category item_purchased  total_orders
0           1  Accessories        Jewelry           171
1           2  Accessories     Sunglasses           161
2           3  Accessories           Belt           161
3           1     Clothing         Blouse           171
4           2     Clothing          Pants           171
5           3     Clothing          Shirt           169
6           1     Footwear        Sandals           160
7           2     Footwear          Shoes           150
8           3     Footwear       Sneakers           145
9           1    Outerwear         Jacket           163
10          2    Outerwear           Coat           161

In [53]:
#Q9Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?


q9 = """
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;
"""
df_q9 = pd.read_sql(q9, engine)
df_q9

  subscription_status  repeat_buyers
0                 Yes            958
1                  No           2518

In [54]:
#Q10. What is the revenue contribution of each age group? 

q10 = """
SELECT age_group,
       SUM(purchase_amount_usd) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
"""
df_q10 = pd.read_sql(q10, engine)
df_q10

     age_group  total_revenue
0         Teen        62143.0
1  MIddle_aged        59197.0
2        Adult        55978.0
3       Senior        55763.0